rails_app/config/routes.rb
# frozen_string_literal: true

require 'sidekiq/pro/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    post 'sign_out', to: 'devise/sessions#destroy'
  end

  # NOTE: may need to add a subdomain constraint, e.g., `constraints: { subdomain: 'api.apotheca.library' }`
  scope module: :api do
    scope :v1, defaults: { format: :json } do
      scope :items, module: :resources do
        get '/:uuid/admin', to: 'items#admin_show', as: :api_item_resource_admin
        get '/:uuid', to: 'items#show', as: :api_item_resource
        get '/lookup/*ark', to: 'items#lookup', constraints: ->(req) { req.params[:ark] =~ %r{\Aark:/\d+/\w+\z} },
                            as: :api_ark_lookup
        get '/:uuid/preview', to: 'items#preview', as: :api_item_preview
        get '/:uuid/pdf', to: 'items#pdf', as: :api_item_pdf
      end
      scope :assets, module: :resources do
        get '/:uuid', to: 'assets#show', as: :api_asset_resource
        get '/:uuid/:file', to: 'assets#file', as: :api_asset_file
      end
    end
    namespace :iiif do
      scope :items do
        get ':uuid/manifest', to: 'items#manifest', as: :api_item_iiif_manifest
      end
    end
  end

  resources :alert_messages, only: %w[index update]
  resources :users, except: :destroy
  scope :bulk_imports do
    post 'file_listing_tool/file_list', to: 'file_listing_tool#file_list'
    get 'file_listing_tool', to: 'file_listing_tool#tool'
  end
  resources :bulk_imports, except: %i[edit destroy update] do
    member do
      patch :cancel, to: 'bulk_imports#cancel'
      get :csv, to: 'bulk_imports#csv'
    end
    resources :imports, only: %w[show] do
      member do
        patch :cancel, to: 'imports#cancel'
      end
    end
  end
  resources :bulk_exports, except: %i[edit update show] do
    member do
      get :cancel, to: 'bulk_exports#cancel'
      get :regenerate, to: 'bulk_exports#regenerate'
    end
  end

  scope :resources do
    resources :items do
      member do
        scope path: :bulk_download, module: :items, controller: :bulk_download, as: :bulk_download do
          get :access
          get :preservation
        end

        get :reorder_assets, to: 'items#reorder_assets'
        get 'file/:type', to: 'items#file', as: :file
        post :refresh_ils_metadata, to: 'items#refresh_ils_metadata'
        post :publish, to: 'items#publish'
        post :unpublish, to: 'items#unpublish'
        post :regenerate_all_derivatives, to: 'items#regenerate_all_derivatives'
      end
    end
    resources :assets, except: :index do
      member do
        get 'file/:type', to: 'assets#file', as: :file
        post :regenerate_derivatives, to: 'assets#regenerate_derivatives'
      end
    end
  end

  resources :system_actions, only: [:index] do
    collection do
      post 'refresh_all_ils_metadata', to: 'refresh_all_ils_metadata'
    end
  end

  resources :events, only: [:index, :show]

  resources :reports, only: [:index]

  authenticate :user, ->(u) { u.can? :manage, :sidekiq_dashboard } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'login', to: 'login#index'

  authenticated do
    root to: 'items#index', as: :authenticated_root
  end

  root to: redirect('/login')

  # Enable Rails built in health check endpoint. This endpoint is not suitable for checking uptime because it doesn't
  # consider all of the application's services.
  get 'up', to: "rails/health#show", as: :rails_health_check
end

rails_app/app/views/shared/_events_listing.html.erb
<% @events = ResourceEvent.where(resource_identifier: resource.id.to_s).order(:completed_at) %>

<h3 id="events" class="mb-3">Events</h3>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Event</th>
        <th scope="col">Initiated By</th>
        <th scope="col">Completed At</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.event_type.titleize %></td>
          <td><%= event.initiated_by %></td>
          <td><%= event.completed_at.to_fs(:display) %></td>
          <td><%= link_to 'Details', "/events/#{event.id}", class: 'btn btn-sm btn-primary' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

rails_app/app/views/shared/_flash_messages.html.erb
<% flash.each do |k, v| %>
  <% type = k.to_sym == :alert ? :warning : :primary %>
  <div class="row">
    <div class="col-sm-12">
      <div class="alert alert-<%= type %> alert-dismissible fade show" role="alert">
        <%= v %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    </div>
  </div>
<% end %>

rails_app/app/views/shared/_header_alert.html.erb
<% if @header_alert&.active? %>
  <%= render(Alert::Component.new(variant: @header_alert.level, class: 'header-alert sticky-top')) do %>
    <%= @header_alert.message %>
  <% end %>
<% end %>

rails_app/app/views/shared/_top_navbar.html.erb
<nav id="site-header" class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Apotheca</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link <%= 'active' if request.path.starts_with?(items_path) || current_page?(root_path) %>"
             href="<%= items_path %>">Items</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <%= 'active' if request.path.starts_with?(bulk_imports_path) %>"
             href="<%= bulk_imports_path %>">Bulk Imports</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <%= 'active' if request.path.starts_with?(bulk_exports_path) %>"
             href="<%= bulk_exports_path %>">Exports</a>
        </li>
        <% if can? :manage, :system_actions %>
          <li class="nav-item">
            <a class="nav-link <%= 'active' if request.path.starts_with?(system_actions_path) %>"
               href="<%= system_actions_path %>">System Actions</a>
          </li>
        <% end %>
        <li class="nav-item">
          <a class="nav-link <%= 'active' if request.path.starts_with?(reports_path) %>"
             href="<%= reports_path %>">Reports</a>
        </li>
        <% if can? :manage, User %>
          <li class="nav-item">
            <a class="nav-link <%= 'active' if request.path.starts_with?(users_path) %>"
               href="<%= users_path %>">Users</a>
          </li>
        <% end %>
        <% if can? :manage, AlertMessage %>
          <li class="nav-item">
            <a class="nav-link <%= 'active' if request.path.starts_with?(alert_messages_path) %>"
               href="<%= alert_messages_path %>">Alerts</a>
          </li>
        <% end %>
        <% if can? :manage, :sidekiq_dashboard %>
          <li class="nav-item">
            <a class="nav-link" href="<%= sidekiq_web_path %>"
               target="_blank">Sidekiq <%= render Icon::Component.new(name: 'box-arrow-up-right') %></a>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user_presenter.full_name %>
            </a>
            <ul class="dropdown-menu dropdown-menu-end <%= 'fixed-top' if @header_alert&.active? %>">
              <li><%= button_to 'Sign Out',
                                sign_out_path(type: current_user.provider),
                                class: 'dropdown-item' %> </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>