rails_app/config/routes.rb
# frozen_string_literal: true

require 'sidekiq/pro/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    post 'sign_out', to: 'devise/sessions#destroy'
  end

  # NOTE: may need to add a subdomain constraint, e.g., `constraints: { subdomain: 'api.apotheca.library' }`
  scope module: :api do
    scope :v1, defaults: { format: :json } do
      scope :items, module: :resources do
        get '/:uuid/admin', to: 'items#admin_show', as: :api_item_resource_admin
        get '/:uuid', to: 'items#show', as: :api_item_resource
        get '/lookup/*ark', to: 'items#lookup', constraints: ->(req) { req.params[:ark] =~ %r{\Aark:/\d+/\w+\z} },
                            as: :api_ark_lookup
        get '/:uuid/preview', to: 'items#preview', as: :api_item_preview
        get '/:uuid/pdf', to: 'items#pdf', as: :api_item_pdf
      end
      scope :assets, module: :resources do
        get '/:uuid', to: 'assets#show', as: :api_asset_resource
        get '/:uuid/:file', to: 'assets#file', as: :api_asset_file
      end
    end
    namespace :iiif do
      scope :items do
        get ':uuid/manifest', to: 'items#manifest', as: :api_item_iiif_manifest
      end
    end
  end

  resources :alert_messages, only: %w[index update]
  resources :users, except: :destroy
  scope :bulk_imports do
    post 'file_listing_tool/file_list', to: 'file_listing_tool#file_list'
    get 'file_listing_tool', to: 'file_listing_tool#tool'
  end
  resources :bulk_imports, except: %i[edit destroy update] do
    member do
      patch :cancel, to: 'bulk_imports#cancel'
      get :csv, to: 'bulk_imports#csv'
    end
    resources :imports, only: %w[show] do
      member do
        patch :cancel, to: 'imports#cancel'
      end
    end
  end
  resources :bulk_exports, except: %i[edit update show] do
    member do
      get :cancel, to: 'bulk_exports#cancel'
      get :regenerate, to: 'bulk_exports#regenerate'
    end
  end

  scope :resources do
    resources :items do
      member do
        scope path: :bulk_download, module: :items, controller: :bulk_download, as: :bulk_download do
          get :access
          get :preservation
        end

        get :reorder_assets, to: 'items#reorder_assets'
        get 'file/:type', to: 'items#file', as: :file
        post :refresh_ils_metadata, to: 'items#refresh_ils_metadata'
        post :publish, to: 'items#publish'
        post :unpublish, to: 'items#unpublish'
        post :regenerate_all_derivatives, to: 'items#regenerate_all_derivatives'
      end
    end
    resources :assets, except: :index do
      member do
        get 'file/:type', to: 'assets#file', as: :file
        post :regenerate_derivatives, to: 'assets#regenerate_derivatives'
      end
    end
  end

  resources :system_actions, only: [:index] do
    collection do
      post 'refresh_all_ils_metadata', to: 'refresh_all_ils_metadata'
    end
  end

  resources :events, only: [:index, :show]

  resources :reports, only: [:index]

  authenticate :user, ->(u) { u.can? :manage, :sidekiq_dashboard } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'login', to: 'login#index'

  authenticated do
    root to: 'items#index', as: :authenticated_root
  end

  root to: redirect('/login')

  # Enable Rails built in health check endpoint. This endpoint is not suitable for checking uptime because it doesn't
  # consider all of the application's services.
  get 'up', to: "rails/health#show", as: :rails_health_check
end

rails_app/app/models/user.rb
# frozen_string_literal: true

# this is a User
class User < ApplicationRecord
  ADMIN_ROLE = 'admin'
  EDITOR_ROLE = 'editor'
  VIEWER_ROLE = 'viewer'
  ROLES = [ADMIN_ROLE, EDITOR_ROLE, VIEWER_ROLE].freeze
  MAX_BULK_EXPORTS = 10

  devise :rememberable, :timeoutable
  if Rails.env.development?
    devise :omniauthable, omniauth_providers: %i[developer saml]
  else
    devise :omniauthable, omniauth_providers: [:saml]
  end

  delegate :can?, :cannot?, to: :ability

  has_many :bulk_exports, foreign_key: 'created_by_id', dependent: :destroy, inverse_of: :created_by
  has_many :bulk_imports, foreign_key: 'created_by_id', dependent: :destroy, inverse_of: :created_by

  before_validation :deduplicate_roles

  validate :require_only_one_role
  validates :roles, inclusion: ROLES
  validates :email, uniqueness: { scope: :provider }, presence: true
  validates :uid, uniqueness: { scope: :provider }, presence: true
  validates :provider, presence: true

  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  scope :active_filter, ->(query) { where(active: query) }
  scope :roles_filter, ->(query) { where('? = ANY (roles)', query.downcase) }
  scope :users_search, ->(query) { where("email || ' ' || first_name || ' ' || last_name ILIKE ?", "%#{query}%") }
  scope :with_exports, -> { joins(:bulk_exports).distinct }
  scope :with_imports, -> { joins(:bulk_imports).distinct }

  # @param [OmniAuth::AuthHash] auth
  # @return [User, nil]
  def self.from_omniauth_saml(auth)
    user = find_by(provider: auth.provider, uid: auth.info.uid.gsub('@upenn.edu', ''))
    return nil unless user

    user.first_name = auth.info.first_name
    user.last_name = auth.info.last_name
    user.email = auth.info.uid
    user
  end

  # @param [OmniAuth::AuthHash] auth
  # @return [User]
  def self.from_omniauth_developer(auth)
    return unless Rails.env.development?

    # we require an email, this is a good enough guess until we get a value from the IdP
    email = "#{auth.info.uid}@upenn.edu"
    where(provider: auth.provider, uid: auth.info.uid, email: email).first_or_create do |user|
      user.uid = auth.info.uid
      user.email = email
      user.first_name = 'DEVELOPER'
      user.last_name = 'ACCOUNT'
      user.active = true
      user.roles << ADMIN_ROLE
    end
  end

  # @return [TrueClass, FalseClass]
  def admin?
    roles.include? ADMIN_ROLE
  end

  # @return [TrueClass, FalseClass]
  def editor?
    roles.include? EDITOR_ROLE
  end

  # @return [TrueClass, FalseClass]
  def viewer?
    roles.include? VIEWER_ROLE
  end

  def ability
    @ability ||= Ability.new(self)
  end

  private

  def deduplicate_roles
    roles.uniq!
  end

  def require_only_one_role
    if roles.length > 1
      errors.add(:roles, 'cannot be multivalued')
    elsif roles.empty?
      errors.add(:roles, 'must be set for a User')
    end
  end
end

rails_app/app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  # custom OmniAuth callbacks
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    skip_forgery_protection only: [:developer, :saml, :failure]

    def saml
      @user = User.from_omniauth_saml(request.env['omniauth.auth'])
      handle_user user: @user, kind: 'PennKey'
    end

    def developer
      @user = User.from_omniauth_developer(request.env['omniauth.auth'])
      handle_user user: @user, kind: 'Developer'
    end

    def failure
      flash.alert = 'Problem with authentication, try again.'
      Honeybadger.notify 'Omniauth failure'
      redirect_to root_path
    end

    private

    # @param [User] user
    # @param [String] kind
    def handle_user(user:, kind:)
      if !user
        redirect_to login_path, notice: 'Contact a site administrator for access.'
      elsif !user.active?
        redirect_to login_path, notice: 'Your account is inactive, contact a site administrator to regain access.'
      elsif user.save
        sign_in_and_redirect user, event: :authentication
        set_flash_message(:notice, :success, kind: kind) if is_navigational_format?
      else
        set_flash_message(:notice, :failure, kind: kind, reason: user.errors.to_a.join(', ')) if is_navigational_format?
        redirect_to login_path
      end
    end
  end
end

rails_app/app/controllers/users_controller.rb
# frozen_string_literal: true

# Controller actions for Users
class UsersController < UIController
  include PerPage

  load_and_authorize_resource

  def index
    @users = User.page(params[:page]).per(per_page)
    @users = @users.users_search(params[:users_search]) if params[:users_search].present?
    @users = @users.active_filter(params[:active_filter]) if params[:active_filter].present?
    @users = @users.roles_filter(params[:roles_filter]) if params[:roles_filter].present?
    @users = PaginatableSetPresenter.new @users
  end

  def show
    @user = UserPresenter.new object: @user
  end

  def new; end

  def create
    @user.update(**user_params, provider: 'saml')
    if @user.save
      flash.notice = "User access granted for #{@user.uid}"
      redirect_to user_path(@user)
    else
      flash.alert = "Problem adding user: #{@user.errors.map(&:full_message).join(', ')}"
      render :edit
    end
  end

  def edit; end

  def update
    @user.update user_params
    if @user.save
      flash.notice = 'User updated'
      redirect_to user_path(@user)
    else
      flash.alert = "Problem updating user: #{@user.errors.map(&:full_message).join(', ')}"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :uid, :email, :active, :roles).tap do |p|
      p[:roles] = Array.wrap(p[:roles]) # roles is expected to be multivalued
      p[:email] = "#{p[:uid]}@upenn.edu" if p[:email].blank?
    end
  end
end

rails_app/app/views/users/_filters.html.erb
<section class="my-4">
    <%= bootstrap_form_tag(url: users_path, method: :get) do |f| %>

      <div class="row align-items-end">
        <div class="col-md-3 col-lg-2">
          <%= f.text_field :users_search,
                           value: params[:users_search],
                           label: 'Search' %>
        </div>

        <div class="col-md-auto">
          <%= f.select :active_filter,
                       options_for_select([['Active', 1], ['Inactive', 0]], selected: params[:active_filter]),
                       include_blank: true,
                       label: 'Status' %>
        </div>

        <div class="col-md-auto">
          <%= f.select :roles_filter,
                       options_for_select(User::ROLES.map(&:titleize), selected: params[:roles_filter]),
                       include_blank: true,
                       label: 'Role' %>
        </div>

        <div class="col-md-auto">
          <%= f.select 'per_page',
                       options_for_select(PerPage::PER_PAGE_OPTIONS,
                                          per_page_from_session(controller_name)),
                       label: 'Per Page' %>
        </div>

        <div class="col my-3 d-flex align-items-center">
          <%= f.submit 'Filter',
                       name: 'filter',
                       class: 'btn btn-primary users-filter-submit' %>

          <%= link_to '',
                      users_path,
                      class: 'btn btn-close btn-sm ms-3',
                      label: 'Reset',
                      hide_label: true %>
        </div>
      </div>
    <% end %>

</section>

rails_app/app/views/users/_form.html.erb
<div class="alert alert-warning">
  Only a PennKey value is required here. Any other values provided will be overwritten with data from the PennKey
  server when the user logs in.
</div>

<%= render(Form::Component.new(model: @user, input_col: { sm: 6 })) do |form| %>
  <% form.with_field(:uid, type: :text, label: 'PennKey') %>
  <% form.with_field(:email, type: :email) %>
  <% form.with_field(:first_name, type: :text) %>
  <% form.with_field(:last_name, type: :text) %>
  <% form.with_field(:roles, type: :select, value: @user.roles.first, choices: User::ROLES) %>
  <% form.with_field(:active, type: :switch) %>
  <% form.with_submit('Save') %>
<% end %>

rails_app/app/views/users/edit.html.erb
<%= render(Breadcrumbs::Component.new) do |component| %>
  <% component.with_breadcrumb(href: '/') do %>Home<% end %>
  <% component.with_breadcrumb(href: users_path) do %>Users<% end %>
  <% component.with_breadcrumb(active: true) do %><%= @user.email %><% end %>
<% end %>

<h2>Edit User</h2>

<%= render 'form' %>

rails_app/app/views/users/index.html.erb
<%= render(Breadcrumbs::Component.new) do |component| %>
  <% component.with_breadcrumb(href: '/') do %>Home<% end %>
  <% component.with_breadcrumb(active: true) do %>Users<% end %>
<% end %>

<%= render(Header::Component.new) do |header| %>
  <%= header.with_title { 'Users' } %>
  <%= header.with_link(href: new_user_path) { 'Add User' } %>
<% end %>

<%= render 'filters' %>

<div class="mb-3">
  <%= page_entries_info @users, entry_name: 'user' %>
</div>

<% unless @users.empty? %>
  <table class="table users-list">
    <thead>
    <tr>
      <th scope="col">Email</th>
      <th scope="col">PennKey</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Roles</th>
      <th scope="col">Active?</th>
      <th scope="col">Created</th>
      <th scope="col">Updated</th>
      <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr class="users-list__user">
          <td><%= link_to user.email, user_path(user) %></td>
          <td><%= user.uid %></td>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.role_names %></td>
          <td><%= user.active_text %></td>
          <td><%= user.created_time %></td>
          <td><%= user.updated_time %></td>
          <td><%= link_to 'Edit', edit_user_path(user), class: 'btn btn-sm btn-outline-primary' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @users %>
<% end %>

rails_app/app/views/users/new.html.erb
<%= render(Breadcrumbs::Component.new) do |component| %>
  <% component.with_breadcrumb(href: '/') do %>Home<% end %>
  <% component.with_breadcrumb(href: users_path) do %>Users<% end %>
  <% component.with_breadcrumb(active: true) do %>New<% end %>
<% end %>

<h2>Add User</h2>

<%= render 'form' %>

rails_app/app/views/users/show.html.erb
<%= render(Breadcrumbs::Component.new) do |component| %>
  <% component.with_breadcrumb(href: '/') do %>Home<% end %>
  <% component.with_breadcrumb(href: users_path) do %>Users<% end %>
  <% component.with_breadcrumb(active: true) do %><%= @user.email %><% end %>
<% end %>

<%= render(Header::Component.new) do |header| %>
  <%= header.with_title { @user.full_name } %>
  <%= header.with_link(href: edit_user_path(@user)) { 'Edit User' } %>
<% end %>

<%= render(StaticFields::Component.new) do |component| %>
  <%= component.with_field(
        label: 'PennKey',
        values: @user.uid
      ) %>
  <%= component.with_field(
        label: 'Email',
        values: @user.email
      ) %>
  <%= component.with_field(
        label: 'Name',
        values: @user.full_name
      ) %>
  <%= component.with_field(
        label: 'Roles',
        values: @user.role_names
      ) %>
  <%= component.with_field(
        label: 'Active?',
        values: @user.active_text
      ) %>
<% end %>