rails_app/config/routes.rb
# frozen_string_literal: true

require 'sidekiq/pro/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    post 'sign_out', to: 'devise/sessions#destroy'
  end

  # NOTE: may need to add a subdomain constraint, e.g., `constraints: { subdomain: 'api.apotheca.library' }`
  scope module: :api do
    scope :v1, defaults: { format: :json } do
      scope :items, module: :resources do
        get '/:uuid/admin', to: 'items#admin_show', as: :api_item_resource_admin
        get '/:uuid', to: 'items#show', as: :api_item_resource
        get '/lookup/*ark', to: 'items#lookup', constraints: ->(req) { req.params[:ark] =~ %r{\Aark:/\d+/\w+\z} },
                            as: :api_ark_lookup
        get '/:uuid/preview', to: 'items#preview', as: :api_item_preview
        get '/:uuid/pdf', to: 'items#pdf', as: :api_item_pdf
      end
      scope :assets, module: :resources do
        get '/:uuid', to: 'assets#show', as: :api_asset_resource
        get '/:uuid/:file', to: 'assets#file', as: :api_asset_file
      end
    end
    namespace :iiif do
      scope :items do
        get ':uuid/manifest', to: 'items#manifest', as: :api_item_iiif_manifest
      end
    end
  end

  resources :alert_messages, only: %w[index update]
  resources :users, except: :destroy
  scope :bulk_imports do
    post 'file_listing_tool/file_list', to: 'file_listing_tool#file_list'
    get 'file_listing_tool', to: 'file_listing_tool#tool'
  end
  resources :bulk_imports, except: %i[edit destroy update] do
    member do
      patch :cancel, to: 'bulk_imports#cancel'
      get :csv, to: 'bulk_imports#csv'
    end
    resources :imports, only: %w[show] do
      member do
        patch :cancel, to: 'imports#cancel'
      end
    end
  end
  resources :bulk_exports, except: %i[edit update show] do
    member do
      get :cancel, to: 'bulk_exports#cancel'
      get :regenerate, to: 'bulk_exports#regenerate'
    end
  end

  scope :resources do
    resources :items do
      member do
        scope path: :bulk_download, module: :items, controller: :bulk_download, as: :bulk_download do
          get :access
          get :preservation
        end

        get :reorder_assets, to: 'items#reorder_assets'
        get 'file/:type', to: 'items#file', as: :file
        post :refresh_ils_metadata, to: 'items#refresh_ils_metadata'
        post :publish, to: 'items#publish'
        post :unpublish, to: 'items#unpublish'
        post :regenerate_all_derivatives, to: 'items#regenerate_all_derivatives'
      end
    end
    resources :assets, except: :index do
      member do
        get 'file/:type', to: 'assets#file', as: :file
        post :regenerate_derivatives, to: 'assets#regenerate_derivatives'
      end
    end
  end

  resources :system_actions, only: [:index] do
    collection do
      post 'refresh_all_ils_metadata', to: 'refresh_all_ils_metadata'
    end
  end

  resources :events, only: [:index, :show]

  resources :reports, only: [:index]

  authenticate :user, ->(u) { u.can? :manage, :sidekiq_dashboard } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'login', to: 'login#index'

  authenticated do
    root to: 'items#index', as: :authenticated_root
  end

  root to: redirect('/login')

  # Enable Rails built in health check endpoint. This endpoint is not suitable for checking uptime because it doesn't
  # consider all of the application's services.
  get 'up', to: "rails/health#show", as: :rails_health_check
end

rails_app/app/models/bulk_import.rb
# frozen_string_literal: true

# Model for BulkImport
class BulkImport < ApplicationRecord
  COMPLETED = 'completed'
  COMPLETED_WITH_ERRORS = 'completed with errors'
  IN_PROGRESS = 'in progress'
  QUEUED = 'queued'
  CANCELLED = 'cancelled'

  PRIORITY_QUEUES = %w[high medium low].freeze
  DEFAULT_PRIORITY = 'medium'

  belongs_to :created_by, class_name: 'User'
  has_many :imports, dependent: :destroy

  validates_associated :created_by, :imports

  attr_accessor :csv_rows

  validates :original_filename, presence: true

  scope :filter_created_by, ->(query) { joins(:created_by).where({ created_by: { email: query } }) }
  scope :filter_created_between, lambda { |start_date, end_date|
    start_date = start_date.present? ? start_date.to_date.beginning_of_day : nil
    end_date = end_date.present? ? end_date.to_date.end_of_day : nil
    where(created_at: start_date..end_date) if start_date || end_date
  }
  scope :search, ->(query) { where('original_filename ILIKE :search OR note ILIKE :search', search: "%#{query}%") }

  paginates_per 10

  def state
    return nil if imports.empty?

    if imports_queued?
      QUEUED
    elsif imports_cancelled?
      CANCELLED
    elsif imports_successful_or_cancelled?
      COMPLETED
    elsif imports_finished_with_failures?
      COMPLETED_WITH_ERRORS
    else
      IN_PROGRESS
    end
  end

  # @param [String] queue
  def create_imports(queue = BulkImport::DEFAULT_PRIORITY)
    import_params = csv_rows.map do |row|
      import = Import.create!(bulk_import: self, import_data: row)
      Array.wrap(import.id)
    end
    ProcessImportJob.set(queue: "import_#{queue}").perform_bulk(import_params)
  end

  # @return [StringIO]
  def csv
    data = imports.map(&:import_data)
    StructuredCSV.generate(data)
  end

  # A bulk import has an empty_csv if the parsed csv cached in csv_rows contains no item data
  # @return [Boolean]
  def empty_csv?
    return true if csv_rows.blank?

    csv_rows.each do |row|
      return false if row.present?
    end
    true
  end

  # @return [Integer]
  def aggregate_processing_time
    imports.sum(:duration)
  end

  # @return [Integer]
  def number_of_errors
    imports.failed.count
  end

  # Determine if the related Imports are all queued
  # @return [TrueClass, FalseClass]
  def imports_queued?
    imports.count.positive? && imports.queued.count == imports.count
  end

  # Determine if any of the related Imports are queued
  def any_imports_queued?
    imports.exists?(state: Import::STATE_QUEUED)
  end

  # Determine if the related Imports are all cancelled
  # @return [TrueClass, FalseClass]
  def imports_cancelled?
    imports.count.positive? && imports.cancelled.count == imports.count
  end

  # Determine if the related Imports are all complete (_not_ processing or queued) and has at least one failed
  # @return [TrueClass, FalseClass]
  def imports_finished_with_failures?
    imports.exists?(state: Import::STATE_FAILED) && imports.where(state: [Import::STATE_QUEUED,
                                                                          Import::STATE_PROCESSING]).blank?
  end

  # Determine if the related Imports are all either successful or cancelled
  # @return [TrueClass, FalseClass]
  def imports_successful_or_cancelled?
    imports.count.positive? && ((imports.successful.count + imports.cancelled.count) == imports.count)
  end

  # @param [User] current_user
  # Cancel all possible child imports
  def cancel_all(current_user)
    imports.queued.each { |import| import.cancel! if import.can_cancel?(current_user) }
  end
end

rails_app/app/controllers/bulk_imports_controller.rb
# frozen_string_literal: true

# controller actions for BulkImport
class BulkImportsController < UIController
  load_and_authorize_resource
  # We have to skip auto-loading for the create action because
  # load_and_authorize_resource expects strong parameters
  skip_load_resource only: :create

  include PerPage

  def index
    @users = User.with_imports
    @bulk_imports = BulkImport.order(created_at: :desc)
                              .page(params[:page]).per(per_page)
                              .includes(:imports, :created_by)

    if params.dig('filter', 'created_by').present?
      @bulk_imports = @bulk_imports.filter_created_by(params.dig('filter', 'created_by'))
    end

    if params.dig('filter', 'start_date').present? || params.dig('filter', 'end_date').present?
      @bulk_imports = @bulk_imports.filter_created_between(
        params.dig('filter', 'start_date'), params.dig('filter', 'end_date')
      )
    end

    @bulk_imports = @bulk_imports.search(params.dig('filter', 'search')) if params.dig('filter', 'search').present?
  end

  def show
    @state = params[:import_state]
    @imports = @bulk_import.imports.page(params[:import_page])
    @imports = @imports.where(state: @state).page(params[:import_page]) if @state
  end

  def new; end

  def create
    @bulk_import = BulkImport.new(created_by: current_user, note: params[:bulk_import][:note])
    uploaded_file = params[:bulk_import][:csv]
    uploaded_file.tempfile.set_encoding('UTF-8')
    @bulk_import.original_filename = uploaded_file.original_filename

    begin
      csv = ImportService::CSV.new(uploaded_file.read)
      assets_csv_files.each do |file|
        csv.add_assets_csv(file.original_filename, file.read)
      end
      csv.valid!
      @bulk_import.csv_rows = csv
    rescue CSV::MalformedCSVError, ImportService::CSV::Error => e
      return redirect_to bulk_imports_path, alert: "Problem creating bulk import: #{e.message}"
    end

    if @bulk_import.save
      @bulk_import.create_imports(safe_queue_name_from(params[:bulk_import][:job_priority].to_s))
      redirect_to bulk_import_path(@bulk_import), notice: 'Bulk import created'
    else
      redirect_to bulk_imports_path,
                  alert: "Problem creating bulk import: #{@bulk_import.errors.map(&:full_message).join(', ')}"
    end
  end

  def cancel
    @bulk_import.cancel_all(current_user)
    redirect_back_or_to bulk_import_path(@bulk_import), notice: 'All queued imports were cancelled'
  end

  def csv
    send_data @bulk_import.csv, type: 'text/csv', filename: @bulk_import.original_filename, disposition: :download
  end

  private

  # @param [String] priority_param
  # @return [String]
  def safe_queue_name_from(priority_param)
    if priority_param.in?(BulkImport::PRIORITY_QUEUES)
      priority_param
    else
      BulkImport::DEFAULT_PRIORITY
    end
  end

  # @return [Array<ActionDispatch::Http::UploadedFile>]
  def assets_csv_files
    params[:bulk_import][:assets_csv_files] || []
  end
end

rails_app/app/views/bulk_imports/_filter.html.erb
<section class="my-4">
<%= bootstrap_form_tag(url: bulk_imports_path, method: 'get') do |form| %>
  <div class="row align-items-end">
    <div class="col-md-3 col-lg-2">
      <%= form.text_field 'filter[search]',
                          value: params.dig('filter', 'search'),
                          label: 'Search' %>
    </div>
    <div class="col-md-auto">
      <%= form.date_field 'filter[start_date]',
                          value: params.dig('filter', 'start_date'),
                          label: 'Start Date' %>
    </div>
    <div class="col-md-auto">
      <%= form.date_field 'filter[end_date]',
                          value: params.dig('filter', 'end_date'),
                          label: 'End Date' %>
    </div>
    <div class="col-md-auto">
      <%= form.select 'filter[created_by]',
                      options_from_collection_for_select(@users, 'email', 'email', params.dig('filter', 'created_by')),
                      selected: params.dig('filter', 'created_by'),
                      include_blank: true,
                      label: 'Created By' %>
    </div>
    <div class="col-md-auto">
      <%= form.select 'per_page',
                      options_for_select(PerPage::PER_PAGE_OPTIONS, per_page_from_session(controller_name)),
                      label: 'Per Page' %>
    </div>
    <div class="col my-3 d-flex align-items-center">
      <%= form.submit 'Filter', name: nil, class: 'btn btn-primary' %>
      <%= link_to '', bulk_imports_path, name: nil, class: 'btn btn-close btn-sm ms-3' %>
    </div>
  </div>
<% end %>
</section>

rails_app/app/views/bulk_imports/_form.html.erb
<%= render(Form::Component.new(model: @bulk_import, disable_with: 'Creating New Bulk Import...', multipart: true, size: :sm)) do |form| %>
  <% form.with_field(:created_by, type: :text, value: current_user.email, disabled: true) %>
  <% form.with_field(:csv, type: :file, required: true) %>
  <% form.with_field(field: 'bulk_import[assets_csv_files][]', type: :file,
                     label: 'Assets CSV(s)',
                     description: 'All Assets CSVs must be uploaded at the same time.',
                     multiple: true, required: false) %>
  <% form.with_field(:note, type: :textarea) %>
  <% form.with_field(field: 'bulk_import[job_priority]', type: :select,
                     choices: BulkImport::PRIORITY_QUEUES, value: BulkImport::DEFAULT_PRIORITY,
                     label: 'Priority') %>

  <% form.with_submit('Create') %>
<% end %>

rails_app/app/views/bulk_imports/index.html.erb
<%= render(Breadcrumbs::Component.new) do |component| %>
  <% component.with_breadcrumb(href: '/') do %>Home<% end %>
  <% component.with_breadcrumb(active: true) do %>Bulk Imports<% end %>
<% end %>

<%= render(Header::Component.new) do |header| %>
  <%= header.with_title { 'Bulk Imports' } %>
  <%= header.with_link(href: file_listing_tool_path) { 'File Listing Tool' } %>
  <% if can?(:create, BulkImport) %>
    <%= header.with_link(href: new_bulk_import_path) { 'New Bulk Import' } %>
  <% end %>
<% end %>

<%= render 'bulk_imports/filter' %>

<div class="mb-3">
  <%= page_entries_info @bulk_imports, entry_name: 'bulk import' %>
</div>

<% if @bulk_imports.any? %>
  <div class="table-responsive">
    <table class="table table-striped bulk-imports-list">
      <thead>
        <tr>
          <th scope="col">Original Filename</th>
          <th scope="col">Created at</th>
          <th scope="col">Created by</th>
          <th scope="col">Imports</th>
          <th scope="col">State</th>
          <th scope="col">Errors</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @bulk_imports.each do |bulk_import| %>
          <tr class="bulk-imports-list__bulk-import">
            <td><%= link_to (bulk_import.original_filename || '[Unknown]'), bulk_import_path(bulk_import) %></td>
            <td><%= bulk_import.created_at.to_fs(:display) %></td>
            <td><%= bulk_import.created_by.email %></td>
            <td><%= bulk_import.imports.length %></td>
            <td><%= bulk_import.state.nil? ? 'No imports' : bulk_import.state.capitalize %></td>
            <td><%= bulk_import.number_of_errors %></td>
            <td class="py-xl-1 text-center">
              <% if bulk_import.any_imports_queued? && can?(:cancel, bulk_import) %>
                <%= render Form::Component.new(name: 'cancel_all_imports', url: cancel_bulk_import_path(bulk_import), method: :patch) do |component| %>
                  <% component.with_submit('Cancel',
                                           confirm: I18n.t('actions.bulk_import.cancel_all.confirm_message'),
                                           variant: :danger, class: 'btn-sm') %>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= paginate @bulk_imports %>

  </div>
<% end %>

rails_app/app/views/bulk_imports/new.html.erb
<%= render(Breadcrumbs::Component.new) do |component| %>
  <% component.with_breadcrumb(href: '/') { 'Home' } %>
  <% component.with_breadcrumb(href: bulk_imports_path) { 'Bulk Imports' } %>
  <% component.with_breadcrumb(active: true) { 'New' } %>
<% end %>

<h2>Create Bulk Import</h2>

<%= render partial: 'form' %>

rails_app/app/views/bulk_imports/show.html.erb
<%= render(Breadcrumbs::Component.new) do |component| %>
  <% component.with_breadcrumb(href: '/') { 'Home' } %>
  <% component.with_breadcrumb(href: bulk_imports_path) { 'Bulk Imports' } %>
  <% component.with_breadcrumb(active: true) { @bulk_import.id } %>
<% end %>

<%= render(Header::Component.new) do |header| %>
  <%= header.with_title { 'Bulk Import' } %>
<% end %>

<%= render(SummaryInfo::Component.new(cols: 4, id: 'bulk-import-dl')) do |component| %>

  <% component.with_field('Original Filename', value_classes: 'd-flex align-items-center') do %>
    <%= @bulk_import.original_filename || '[Unknown]' %>
    <%= link_to(csv_bulk_import_path, title: 'Download CSV', class: 'mx-2 lh-1') do %>
      <%= render Icon::Component.new(name: 'download', size: '22px') %>
    <% end %>
  <% end %>

  <% component.with_field(spacer: true) %>

  <% component.with_field('Total Imports') do %>
    <%= @bulk_import.imports.count %>
  <% end %>

  <% component.with_field('Total Processing Time') do %>
    <% if @bulk_import.state.in? [BulkImport::COMPLETED, BulkImport::COMPLETED_WITH_ERRORS] %>
      <% processing_time = @bulk_import.aggregate_processing_time %>
      <%= processing_time.zero? ? '[Unknown]' : distance_of_time(processing_time) %>
    <% else %>
      [Unknown]
    <% end %>
  <% end %>

  <% component.with_field('Note') do %>
    <%= @bulk_import.note || '[None]' %>
  <% end %>

  <% component.with_field('ID') do %>
    <%= @bulk_import.id %>
  <% end %>

  <% component.with_field('Created By') do %>
    <%= @bulk_import.created_by.email %>
  <% end %>

  <% component.with_field('Created At') do %>
    <%= @bulk_import.created_at.to_fs(:display) %>
  <% end %>
<% end %>

<div class="d-flex flex-column flex-sm-row justify-content-sm-between mb-4">
  <h4 class="mb-3 mb-sm-0">Imports</h4>
  <% if @bulk_import.any_imports_queued? &&  can?(:cancel, @bulk_import) %>
    <%= render Form::Component.new(name: 'cancel_all_imports', url: cancel_bulk_import_path(@bulk_import), method: :patch) do |component| %>
      <% component.with_submit('Cancel All Queued Imports',
                               confirm: I18n.t('actions.bulk_import.cancel_all.confirm_message'),
                               variant: :secondary,
                               class: 'btn-sm') %>
    <% end %>
  <% end %>
</div>

<ul class="nav nav-tabs" id="import-states-tabs">
  <li class="nav-item" role="presentation">
    <a class="nav-link <%= @state.nil? ? 'active' : '' %>"
       href="<%= bulk_import_path(@bulk_import) %>">
      All
      <span class="badge">
      <%= @bulk_import.imports.count %>
      </span>
    </a>
  </li>
  <% Import.aasm.states.each do |s| %>
    <li role="presentation" class="nav-item">
      <a class="nav-link <%= @state.eql?(s.name.to_s) ? 'active' : '' %><%= @bulk_import.imports.where(state: s.name.to_s).count.zero? ? 'disabled' : '' %>"
         href="<%= @bulk_import.imports.where(state: s.name.to_s).count.positive? ? url_for(import_state: s) : '' %>">
        <%= s.name.to_s.titleize %>
        <span class="badge text-bg-secondary"><%= @bulk_import.imports.where(state: s.name.to_s).count %></span>
      </a>
    </li>
  <% end %>
</ul>

<div class="table-responsive">
  <table class="table table-striped" id="imports-table">
    <thead>
    <tr>
      <th>ID</th>
      <th>State</th>
      <th>Human Readable Name</th>
      <th>Unique Identifier</th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @imports&.each do |import| %>
      <tr>
        <td><%= import.id %></td>
        <td><%= import.state.titleize %></td>
        <td>
            <%= import.human_readable_name %>
        </td>
        <td>
          <%= import.resource.present? ? link_to(import.resource.unique_identifier, item_path(import.resource)) : '[Unknown]' %>
        </td>
        <td>
          <%= link_to 'Details', bulk_import_import_path(@bulk_import, import), class: 'btn btn-sm btn-primary' %>
        </td>
        <td>
          <% if import.can_cancel?(current_user) %>
            <%= render Form::Component.new(name: 'cancel_import', url: cancel_bulk_import_import_path(import.bulk_import, import), method: :patch) do |component| %>
              <% component.with_submit('Cancel', confirm: I18n.t('actions.import.cancel.confirm_message'),
                                                 variant: :secondary, class: 'btn-sm') %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<div class="row">
  <div class="col-md-6">
    <%= paginate @imports, param_name: :import_page %>
  </div>
  <div class="col-md-6">
    <div class="pull-right">
      <%= page_entries_info @imports %>
    </div>
  </div>
</div>