rails_app/config/routes.rb
# frozen_string_literal: true

require 'sidekiq/pro/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    post 'sign_out', to: 'devise/sessions#destroy'
  end

  # NOTE: may need to add a subdomain constraint, e.g., `constraints: { subdomain: 'api.apotheca.library' }`
  scope module: :api do
    scope :v1, defaults: { format: :json } do
      scope :items, module: :resources do
        get '/:uuid/admin', to: 'items#admin_show', as: :api_item_resource_admin
        get '/:uuid', to: 'items#show', as: :api_item_resource
        get '/lookup/*ark', to: 'items#lookup', constraints: ->(req) { req.params[:ark] =~ %r{\Aark:/\d+/\w+\z} },
                            as: :api_ark_lookup
        get '/:uuid/preview', to: 'items#preview', as: :api_item_preview
        get '/:uuid/pdf', to: 'items#pdf', as: :api_item_pdf
      end
      scope :assets, module: :resources do
        get '/:uuid', to: 'assets#show', as: :api_asset_resource
        get '/:uuid/:file', to: 'assets#file', as: :api_asset_file
      end
    end
    namespace :iiif do
      scope :items do
        get ':uuid/manifest', to: 'items#manifest', as: :api_item_iiif_manifest
      end
    end
  end

  resources :alert_messages, only: %w[index update]
  resources :users, except: :destroy
  scope :bulk_imports do
    post 'file_listing_tool/file_list', to: 'file_listing_tool#file_list'
    get 'file_listing_tool', to: 'file_listing_tool#tool'
  end
  resources :bulk_imports, except: %i[edit destroy update] do
    member do
      patch :cancel, to: 'bulk_imports#cancel'
      get :csv, to: 'bulk_imports#csv'
    end
    resources :imports, only: %w[show] do
      member do
        patch :cancel, to: 'imports#cancel'
      end
    end
  end
  resources :bulk_exports, except: %i[edit update show] do
    member do
      get :cancel, to: 'bulk_exports#cancel'
      get :regenerate, to: 'bulk_exports#regenerate'
    end
  end

  scope :resources do
    resources :items do
      member do
        scope path: :bulk_download, module: :items, controller: :bulk_download, as: :bulk_download do
          get :access
          get :preservation
        end

        get :reorder_assets, to: 'items#reorder_assets'
        get 'file/:type', to: 'items#file', as: :file
        post :refresh_ils_metadata, to: 'items#refresh_ils_metadata'
        post :publish, to: 'items#publish'
        post :unpublish, to: 'items#unpublish'
        post :regenerate_all_derivatives, to: 'items#regenerate_all_derivatives'
      end
    end
    resources :assets, except: :index do
      member do
        get 'file/:type', to: 'assets#file', as: :file
        post :regenerate_derivatives, to: 'assets#regenerate_derivatives'
      end
    end
  end

  resources :system_actions, only: [:index] do
    collection do
      post 'refresh_all_ils_metadata', to: 'refresh_all_ils_metadata'
    end
  end

  resources :events, only: [:index, :show]

  resources :reports, only: [:index]

  authenticate :user, ->(u) { u.can? :manage, :sidekiq_dashboard } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'login', to: 'login#index'

  authenticated do
    root to: 'items#index', as: :authenticated_root
  end

  root to: redirect('/login')

  # Enable Rails built in health check endpoint. This endpoint is not suitable for checking uptime because it doesn't
  # consider all of the application's services.
  get 'up', to: "rails/health#show", as: :rails_health_check
end

rails_app/app/controllers/api/iiif/items_controller.rb
# frozen_string_literal: true

module API
  module IIIF
    # API actions for Item-level IIIF-compliant responses
    class ItemsController < APIController
      include ItemLoadable

      # /iiif/items/:uuid/manifest
      def manifest
        manifest = @item.iiif_v3_manifest

        raise FileNotFound, I18n.t('api.exceptions.file_not_found') unless manifest

        response.headers['Access-Control-Allow-Origin'] = '*'
        manifest_file_id = @item.iiif_v3_manifest.file_id

        serve_json(manifest_file_id)
      end
    end
  end
end

rails_app/app/controllers/api/resources/items_controller.rb
# frozen_string_literal: true

module API
  module Resources
    # API actions for ItemResources
    class ItemsController < APIController
      include ItemLoadable

      class InvalidSize < InvalidParameterError; end

      before_action :parse_size!, only: :preview

      DEFAULT_SIZE = 200
      MAX_SIZE = 600

      # renders json with additional metadata required to import a record in a local environment
      def admin_show; end

      def show; end

      def lookup
        render :show
      end

      # Returns preview image for Item. If requested image size is 200,200 or nil redirects to
      # thumbnail, otherwise redirects to IIIF image service.
      def preview
        if @width == DEFAULT_SIZE && @height == DEFAULT_SIZE && @item.thumbnail_image?
          filename = "#{@item.presenter.parameterize}-thumbnail.jpeg"
          redirect_to_presigned_url @item.thumbnail.thumbnail.file_id, filename
        elsif @item.thumbnail&.iiif_image
          redirect_to_iiif_image_server @item.thumbnail, "!#{@width},#{@height}"
        else
          raise FileNotFound, I18n.t('api.exceptions.file_not_found')
        end
      end

      def pdf
        pdf_derivative = @item.pdf

        raise FileNotFound, I18n.t('api.exceptions.file_not_found') unless pdf_derivative

        filename = "#{@item.presenter.parameterize}.pdf"

        redirect_to_presigned_url pdf_derivative.file_id, filename
      end

      private

      def parse_size!
        size = /^(\d{1,3}),(\d{1,3})$/.match(params.fetch(:size, "#{DEFAULT_SIZE},#{DEFAULT_SIZE}"))

        raise InvalidSize, I18n.t('api.exceptions.invalid_param.size') unless size

        @width = size[1].to_i
        @height = size[2].to_i

        raise InvalidSize, I18n.t('api.exceptions.invalid_param.size') if @width > MAX_SIZE || @height > MAX_SIZE
      end
    end
  end
end

rails_app/app/controllers/items/bulk_download_controller.rb
# frozen_string_literal: true

module Items
  # Actions to bulk download files from all of an Item's child Assets.
  class BulkDownloadController < UIController
    include ItemLoadable

    before_action :load_item, :authorize_bulk_download

    # Download the preservation file of each related asset.
    def preservation
      zip_kit_stream(filename: "#{@item.human_readable_name.parameterize}.zip") do |zip|
        @item.assets.each do |asset|
          next if asset.preservation_file_id.blank?

          file = Valkyrie::StorageAdapter.find_by id: asset.preservation_file_id
          zip.write_file(asset.original_filename) do |sink|
            IO.copy_stream(file.io, sink)
          end
        end
      rescue StandardError => e
        raise 'Error downloading preservation files', cause: e
      end
    end

    # Download the access file of each related asset. In the case of images, a JPEG
    # is fetched from the IIIF serverless service.
    def access
      zip_kit_stream(filename: "#{@item.human_readable_name.parameterize}-access.zip") do |zip|
        @item.assets.each do |asset|
          add_access_file(zip, asset)
        end
      rescue StandardError => e
        raise 'Error downloading access files', cause: e
      end
    end

    private

    # Adding access file to zip.
    # In cases where there is no access or iiif_image derivative, no access copy is added.
    def add_access_file(zip, asset)
      if asset.access
        add_access_derivative(zip, asset)
      elsif asset.iiif_image
        add_iiif_image(zip, asset)
      end
    end

    # Adding access derivative to zip.
    def add_access_derivative(zip, asset)
      file = Valkyrie::StorageAdapter.find_by id: asset.access.file_id
      filename = "#{File.basename(asset.original_filename, '.*')}.#{asset.access.extension}"

      zip.write_file(filename) do |sink|
        IO.copy_stream(file.io, sink)
      end
    end

    # Adding JPEG from IIIF Image Service to zip.
    def add_iiif_image(zip, asset)
      uri = URI(asset.iiif_image_url)
      filename = "#{File.basename(asset.original_filename, '.*')}.jpg"

      zip.write_file(filename) do |sink|
        Net::HTTP.get_response(uri) do |response|
          response.read_body(sink)
        end
      end
    end

    def authorize_bulk_download
      authorize! :read, @item
    end
  end
end

rails_app/app/controllers/items_controller.rb
# frozen_string_literal: true

# controller actions for Item stuff
class ItemsController < ResourcesController
  before_action :load_item_and_change_set, except: :index
  before_action :load_assets, only: %i[show edit reorder_assets]
  before_action :configure_pagination, only: :index
  before_action :store_rows, only: :index

  authorize_resource :item_resource, parent: false

  rescue_from 'Valkyrie::Persistence::ObjectNotFoundError', with: :error_redirect

  def index
    @container = solr_query_service.custom_queries.item_index parameters: search_params
  end

  def show; end

  def new; end

  def edit; end

  def create
    CreateItem.new.call(created_by: current_user.email, **item_params) do |result|
      result.success do |resource|
        flash.notice = I18n.t('actions.item.create.success')
        redirect_to item_path(resource)
      end

      result.failure do |failure|
        render_failure(failure, :new)
      end
    end
  end

  def update
    UpdateItem.new.call(id: params[:id], updated_by: current_user.email, **item_params) do |result|
      result.success do |resource|
        flash.notice = I18n.t('actions.item.update.success')
        redirect_to item_path(resource, anchor: params[:form])
      end

      result.failure do |failure|
        render_failure(failure, :edit)
      end
    end
  end

  def destroy
    DeleteItem.new.call(id: params[:id], deleted_by: current_user.email) do |result|
      result.success do
        flash.notice = I18n.t('actions.item.delete.success')
        redirect_to items_path
      end
      result.failure do |failure|
        render_failure(failure, :show)
      end
    end
  end

  def reorder_assets; end

  def file
    case params[:type]
    when *ItemResource::DERIVATIVE_TYPES
      serve_derivative_file resource: @item, type: params[:type].to_sym
    else
      raise UnsupportedFileType, 'Type is not supported'
    end
  end

  def refresh_ils_metadata
    if RefreshIlsMetadataJob.perform_async(@item.id.to_s, current_user.email)
      redirect_to item_path(@item), notice: I18n.t('actions.item.refresh_ILS.success')
    else
      redirect_to items_path(@item), alert: I18n.t('actions.item.refresh_ILS.failure')
    end
  end

  def publish
    if PublishItemJob.perform_async(@item.id.to_s, current_user.email)
      redirect_to item_path(@item), notice: I18n.t('actions.item.publish.success')
    else
      redirect_to items_path(@item), alert: I18n.t('actions.item.publish.failure')
    end
  end

  def unpublish
    UnpublishItem.new.call(id: params[:id], updated_by: current_user.email) do |result|
      result.success do |resource|
        flash.notice = I18n.t('actions.item.unpublish.success')
        redirect_to item_path(resource)
      end
      result.failure do |failure|
        render_failure(failure, :show)
      end
    end
  end

  def regenerate_all_derivatives
    if GenerateAllDerivativesJob.perform_async(@item.id.to_s, current_user.email)
      redirect_to item_path(@item), notice: I18n.t('actions.item.regenerate_all_derivatives.success')
    else
      redirect_to item_path(@item), notice: I18n.t('actions.item.regenerate_all_derivatives.failure')
    end
  end

  private

  # Explicitly set the default per page for initial page load (when there are no params) only for the ItemResource
  # case. With AR models, this config can be specified in the model. I do this here to avoid setting a default app-wide
  # config that might later be altered and break proper page counts when rendering the paginator in the item index.
  def configure_pagination
    Kaminari.configure do |config|
      config.default_per_page = Solr::QueryMaps::Item::ROWS_OPTIONS.min
    end
  end

  def store_rows
    if params[:rows].present?
      session[:item_rows] = params[:rows]
    else
      params[:rows] = session[:item_rows]
    end
  end

  # Handle Failure response from transaction. Set appropriate ivars based on Failure contents and template to render.
  def render_failure(failure, template)
    load_item_and_change_set failure[:change_set]
    load_assets if [:edit, :show].include?(template)

    @error = failure
    @errors_for = params[:form]

    render template
  end

  # Load item and change_set ivars for views. Use ItemPresenter for all views, load ILS metadata only as needed.
  # @param [ItemChangeSet] change_set, optional
  def load_item_and_change_set(change_set = nil)
    resource = if change_set
                 change_set.resource
               elsif params[:id]
                 pg_query_service.find_by(id: params[:id])
               else
                 ItemResource.new
               end
    @item = resource.presenter
    @change_set = change_set || ItemChangeSet.new(resource)
  end

  def load_assets
    @arranged_assets = @item.arranged_assets
    @unarranged_assets = @item.unarranged_assets
  end

  # @param [StandardError] exception
  def error_redirect(exception)
    redirect_to items_path, notice: "Problem loading page: #{exception.message}"
  end

  def item_params
    metadata_fields = ItemResource::DescriptiveMetadata::Fields::CONFIG.transform_values do |type|
      case type
      when :text
        [:value]
      when :term
        [:value, :uri]
      when :name
        [:value, :uri, { role: [:value, :uri] }]
      end
    end

    params.require(:item).permit(
      :human_readable_name, :thumbnail_asset_id, :ocr_strategy,
      internal_notes: [],
      descriptive_metadata: metadata_fields,
      structural_metadata: [
        :viewing_direction, :viewing_hint,
        { arranged_asset_ids: [] }
      ]
    )
  end

  def search_params
    params.permit(:keyword, :rows, :page, filter: {}, sort: {}, search: {})
  end

  # Custom derivative filename.
  #
  # @param [DerivativeResource] derivative
  # @return [String]
  def derivative_filename(derivative)
    "#{@item.human_readable_name.parameterize}.#{derivative.extension}"
  end

  # @return [Valkyrie::MetadataAdapter]
  def solr_query_service
    @solr_query_service ||= Valkyrie::MetadataAdapter.find(:index_solr).query_service
  end
end

rails_app/app/views/items/_actions.html.erb
<%= render(ActionsTable::Component.new) do |component| %>
  <% if can? :publish, @item %>
    <%= component.with_action(description: I18n.t('actions.item.publish.description')) do |action| %>
      <% action.with_form_component(name: 'publish_item', url: publish_item_path(@item, anchor: 'actions'), method: :post) do |form_component| %>
        <% form_component.with_error(@error) if @errors_for == 'publish_item' %>
        <% form_component.with_submit('Publish Item', confirm: I18n.t('actions.item.publish.confirm_message'), variant: :primary) %>
      <% end %>
    <% end %>
  <% end %>

  <% if can? :unpublish, @item %>
    <%= component.with_action(description: I18n.t('actions.item.unpublish.description')) do |action| %>
      <% action.with_form_component(name: 'unpublish_item', url: unpublish_item_path(@item, anchor: 'actions'), method: :post) do |form_component| %>
        <% form_component.with_error(@error) if @errors_for == 'unpublish_item' %>
        <% form_component.with_submit('Unpublish Item',
                                      confirm: I18n.t('actions.item.unpublish.confirm_message'),
                                      disabled: !@item.published,
                                      variant: :primary) %>
      <% end %>
    <% end %>
  <% end %>

  <% if can?(:refresh_ils_metadata, @item) %>
    <%= component.with_action(description: I18n.t('actions.item.refresh_ILS.description')) do |action| %>
      <% action.with_form_component(name: 'refresh_ILS_metadata',
                                    url: refresh_ils_metadata_item_path(@item, anchor: 'actions'),
                                    method: :post) do |form_component| %>
        <% form_component.with_error(@error) if @errors_for == 'refresh_ILS_metadata' %>
        <% form_component.with_submit('Refresh ILS Metadata',
                                      confirm: I18n.t('actions.item.refresh_ILS.confirm_message'),
                                      disabled: @item.descriptive_metadata.bibnumber.blank?,
                                      variant: :primary) %>
      <% end %>
    <% end %>
  <% end %>

  <% if can?(:regenerate_all_derivatives, @item) %>
    <%= component.with_action(description: I18n.t('actions.item.regenerate_all_derivatives.description')) do |action| %>
      <% action.with_form_component(name: 'regenerate_all_derivatives',
                                    url: regenerate_all_derivatives_item_path(@item, anchor: 'actions'),
                                    method: :post) do |form_component| %>
        <% form_component.with_error(@error) if @errors_for == 'regenerate_all_derivatives' %>
        <% form_component.with_submit('Regenerate All Derivatives',
                                      confirm: I18n.t('actions.item.regenerate_all_derivatives.confirm_message'),
                                      variant: :primary) %>
      <% end %>
    <% end %>
  <% end %>

  <% if can?(:delete, @item) %>
    <%= component.with_action(description: I18n.t('actions.item.delete.description')) do |action| %>
      <% action.with_form_component(name: 'delete_item', url: item_path(@item, anchor: 'actions'),
                                    method: :delete) do |form_component| %>
        <% form_component.with_error(@error) if @errors_for == 'delete_item' %>
        <% form_component.with_submit('Delete Item',
                                      confirm: I18n.t('actions.item.delete.confirm_message'),
                                      variant: :danger) %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

rails_app/app/views/items/_administrative_info.erb
<%= render(Header::Component.new) do |header| %>

  <%= header.with_title(tag: :h3) { 'Administrative Information' } %>
  <%= header.with_link(href: edit_item_path(@item, anchor: 'administrative-info')) { 'Edit' } if can? :update, @item %>
<% end %>

<%= render(StaticFields::Component.new) do |component| %>
  <% component.with_field(label: 'Human Readable Name', values: @item.human_readable_name) %>
  <% component.with_field(label: 'OCR Strategy', values: @item.ocr_strategy) %>
  <% component.with_field(label: 'Internal Notes', values: @item.internal_notes) %>
  <% component.with_field(label: 'First Published At', values: @item.first_published_at&.to_fs(:display)) %>
  <% component.with_field(label: 'Last Published At', values: @item.last_published_at&.to_fs(:display)) %>
<% end %>

rails_app/app/views/items/_administrative_info_form.html.erb
<h3>Administrative Information</h3>

<%= render(Form::Component.new(url: item_path(@item, anchor: 'administrative-info'),
                               name: 'administrative-info',
                               model: @change_set,
                               size: :sm)) do |form| %>
  <% form.with_error(@error) if @errors_for == 'administrative-info' %>

  <% form.with_field(:human_readable_name, type: :text) %>
  <% form.with_field(:ocr_strategy, type: :select, choices: ItemChangeSet::OCR_STRATEGIES, include_blank: true) %>
  <% form.with_field(:internal_notes, type: :text) %>
  <% form.with_field(:first_published_at, value: @item.first_published_at&.to_fs(:display), type: :readonly) %>
  <% form.with_field(:last_published_at, value: @item.last_published_at&.to_fs(:display), type: :readonly) %>

  <% form.with_submit('Save') %>
<% end %>

rails_app/app/views/items/_assets_list.html.erb
<%= render(Header::Component.new) do |header| %>
  <%= header.with_title(tag: :h3) { 'Assets' } %>
  <%= header.with_link(href: new_asset_path(item_id: @item.id)) { 'Add Asset' } if can? :create, AssetResource %>
  <%= header.with_link(href: reorder_assets_item_path(@item)) { 'Arrange Assets' } if can? :update, @item %>
  <%= header.with_link(href: preservation_bulk_download_item_path(@item)) { 'Download Preservation Files' } if @item.preservation_bulk_download? %>
  <%= header.with_link(href: access_bulk_download_item_path(@item)) { 'Download Access Files' } if @item.access_bulk_download? %>
  <%= header.with_link(href: '#assets-sidebar',
                       'class': 'd-lg-none',
                       'aria-controls': 'assets-sidebar',
                       'data-bs-toggle': 'offcanvas',
                       'role': 'button') { 'All Assets' } %>
<% end %>

<%= render(AssetsList::Component.new(item: @item, user: current_user)) do |component| %>
  <%= component.with_arranged_cards_section(assets: @arranged_assets) %>
  <%= component.with_unarranged_cards_section(assets: @unarranged_assets) %>
  <%= component.with_arranged_nav_section(assets: @arranged_assets) %>
  <%= component.with_unarranged_nav_section(assets: @unarranged_assets) %>
<% end %>

rails_app/app/views/items/_descriptive_metadata_form.html.erb
<h3>Descriptive Metadata</h3>

<%= render(Form::Component.new(url: item_path(@item, anchor: 'descriptive-metadata'), model: @change_set,
                               name: 'descriptive-metadata', size: :sm)) do |form| %>
  <% form.with_error(@error) if @errors_for == 'descriptive-metadata' %>

  <% ItemResource::DescriptiveMetadata::Fields::CONFIG.each do |field, type| %>
    <% config = type == :name ? { type: :term, subfields: { role: { type: :term } } } : { type: type } %>

    <% form.with_field(:descriptive_metadata, field, type: :descriptive_metadata, config: config) %>
  <% end %>

  <% form.with_submit('Save') %>
<% end %>

rails_app/app/views/items/_header_info.html.erb
<%= render(SummaryInfo::Component.new) do |component| %>

  <% component.with_field('Unique Identifier') do %>
    <%= @item.unique_identifier %>
  <% end %>

  <% component.with_field('Published') do %>
    <% if @item.published %>
      <span>Yes</span>
      <a href="<%= PublishingService::Endpoint.digital_collections.item_url(@item.id) %>"
         target="_blank"
         class="link-underline link-underline-opacity-0">
        (View in Digital Collections)
      </a>
    <% else %>
      No
    <% end %>
  <% end %>

  <% component.with_field('Created By') do %>
    <%= @item.created_by %>
  <% end %>

  <% component.with_field('Created At') do %>
    <%= @item.date_created&.to_fs(:display) %>
  <% end %>

  <% component.with_field('Updated By') do %>
    <%= @item.updated_by %>
  <% end %>

  <% component.with_field('Updated At') do %>
    <%= @item.date_updated&.to_fs(:display) %>
  <% end %>
<% end %>

rails_app/app/views/items/_new_form.html.erb
<%= render(Form::Component.new(model: @change_set, size: :sm)) do |form| %>
  <% form.with_error(@error) %>

  <% form.with_section do |section| %>
    <% section.with_title { 'Administrative Fields' } %>
    <% section.with_field(:human_readable_name, type: :text) %>
    <% section.with_field(:internal_notes, type: :text) %>
  <% end %>

  <% form.with_section do |section| %>
    <% section.with_title { 'Descriptive Metadata' } %>

    <% ItemResource::DescriptiveMetadata::Fields::CONFIG.each do |field, type| %>
      <% config = type == :name ? { type: :term, subfields: { role: { type: :term } } } : { type: type } %>

      <% section.with_field(:descriptive_metadata, field, type: :descriptive_metadata, config: config) %>
    <% end %>
  <% end %>

  <% form.with_section do |section| %>
    <% section.with_title { 'Structural Metadata' } %>

    <% section.with_field(:structural_metadata, :viewing_hint,
                          type: :select,
                          choices: ItemChangeSet::StructuralMetadataChangeSet::VIEWING_HINTS,
                          include_blank: true) %>

    <% section.with_field(:structural_metadata, :viewing_direction,
                          type: :select,
                          choices: ItemChangeSet::StructuralMetadataChangeSet::VIEWING_DIRECTIONS,
                          include_blank: true) %>
  <% end %>

  <% form.with_submit('Save') %>
<% end %>

rails_app/app/views/items/_search_form.html.erb
<%= render(ItemSearch::Component.new(url: items_path, response_container: container)) %>

rails_app/app/views/items/_structural_metadata.html.erb
<%= render(Header::Component.new) do |header| %>
  <%= header.with_title(tag: :h3) { 'Structural Metadata' } %>
  <%= header.with_link(href: edit_item_path(@item, anchor: 'structural-metadata')) { 'Edit' } if can? :update, @item %>
<% end %>

<%= render(StaticFields::Component.new) do |component| %>
  <% component.with_field(
       label: 'Viewing Hint',
       values: @item.structural_metadata.viewing_hint
     ) %>
  <% component.with_field(
       label: 'Viewing Direction',
       values: @item.structural_metadata.viewing_direction
     ) %>
<% end %>

rails_app/app/views/items/_structural_metadata_form.html.erb
<h3>Structural Metadata</h3>

<%= render(Form::Component.new(url: item_path(@item, anchor: 'structural-metadata'),
                               name: 'structural-metadata',
                               model: @change_set,
                               input_col: { sm: 3 },
                               size: :sm)) do |form| %>
  <% form.with_error(@error) if @errors_for == 'structural-metadata' %>

  <% form.with_field(:structural_metadata, :viewing_hint,
                     type: :select,
                     choices: ItemChangeSet::StructuralMetadataChangeSet::VIEWING_HINTS,
                     include_blank: true) %>

  <% form.with_field(:structural_metadata, :viewing_direction,
                     type: :select,
                     choices: ItemChangeSet::StructuralMetadataChangeSet::VIEWING_DIRECTIONS,
                     include_blank: true) %>

  <% form.with_submit('Save') %>
<% end %>

rails_app/app/views/items/index.html.erb
<%= render(Breadcrumbs::Component.new) do |component| %>
  <% component.with_breadcrumb(href: '/') do %>Home<% end %>
  <% component.with_breadcrumb(active: true) do %>Items<% end %>
<% end %>

<%= render(Header::Component.new) do |header| %>
  <% header.with_title { 'Items' } %>
  <% header.with_link(href: new_item_path) { 'Create Item' } if can? :create, ItemResource %>
<% end %>

<%= render partial: 'search_form', locals: { container: @container } %>

<hr>

<%= page_entries_info @container.paginator, entry_name: 'result' %>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Human Readable Name</th>
        <th>Title</th>
        <th>Collection(s)</th>
        <th>Unique Identifier</th>
        <th>Created By</th>
        <th>Published</th>
      </tr>
    </thead>
    <tbody>
      <% @container.documents.each do |item| %>
        <tr>
          <td><%= link_to item.human_readable_name, item_path(item.id) %></td>
          <td>
            <ul class="list-unstyled mb-0">
              <% item.descriptive_metadata.title.each.with_index do |t, i| %>
                <%= tag.li(t[:value], class: i.zero? ? '' : 'pt-2') %>
              <% end %>
            </ul>
          </td>
          <td>
            <ul class="list-unstyled mb-0">
              <% item.descriptive_metadata.collection.each.with_index do |c, i| %>
                <%= tag.li(c[:value], class: i.zero? ? '' : 'pt-2') %>
              <% end %>
            </ul>
          </td>
          <td><%= item.unique_identifier %></td>
          <td><%= item.created_by %></td>
          <td><%= item.published ? 'Yes' : 'No' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= paginate @container.paginator %>

rails_app/app/views/items/new.html.erb
<%= render(Breadcrumbs::Component.new) do |component| %>
  <% component.with_breadcrumb(href: '/') { 'Home' } %>
  <% component.with_breadcrumb(href: items_path) { 'Items' } %>
  <% component.with_breadcrumb(active: true) { 'New' } %>
<% end %>

<h2>Create Item</h2>

<%= render partial: 'new_form' %>